export const data = JSON.parse("{\"key\":\"v-307c4264\",\"path\":\"/interview/designpattern.html\",\"title\":\"设计模式\",\"lang\":\"en-US\",\"frontmatter\":{\"summary\":\"设计模式; 一、UML类图; 1. 泛化关系; 2. 实现关系; 3. 依赖关系; 4. 聚合关系; 5. 关联关系; 二、创建型模式; 1. 简单工厂模式; 2. 工厂方法模式; 3. 抽象工厂模式; 4. 单例模式; 三、结构型模式; 1. 适配器模式; 2. 装饰模式; 3. 代理模式; 四、行为型模式; 1. 策略模式; 2. 观察者模式; 设计模式\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.bmrs.top/interview/designpattern.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"编码人生\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"设计模式\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"一、UML类图\",\"slug\":\"一、uml类图\",\"link\":\"#一、uml类图\",\"children\":[{\"level\":3,\"title\":\"1. 泛化关系\",\"slug\":\"_1-泛化关系\",\"link\":\"#_1-泛化关系\",\"children\":[]},{\"level\":3,\"title\":\"2. 实现关系\",\"slug\":\"_2-实现关系\",\"link\":\"#_2-实现关系\",\"children\":[]},{\"level\":3,\"title\":\"3. 依赖关系\",\"slug\":\"_3-依赖关系\",\"link\":\"#_3-依赖关系\",\"children\":[]},{\"level\":3,\"title\":\"4. 聚合关系\",\"slug\":\"_4-聚合关系\",\"link\":\"#_4-聚合关系\",\"children\":[]},{\"level\":3,\"title\":\"5. 关联关系\",\"slug\":\"_5-关联关系\",\"link\":\"#_5-关联关系\",\"children\":[]}]},{\"level\":2,\"title\":\"二、创建型模式\",\"slug\":\"二、创建型模式\",\"link\":\"#二、创建型模式\",\"children\":[{\"level\":3,\"title\":\"1. 简单工厂模式\",\"slug\":\"_1-简单工厂模式\",\"link\":\"#_1-简单工厂模式\",\"children\":[]},{\"level\":3,\"title\":\"2. 工厂方法模式\",\"slug\":\"_2-工厂方法模式\",\"link\":\"#_2-工厂方法模式\",\"children\":[]},{\"level\":3,\"title\":\"3. 抽象工厂模式\",\"slug\":\"_3-抽象工厂模式\",\"link\":\"#_3-抽象工厂模式\",\"children\":[]},{\"level\":3,\"title\":\"4. 单例模式\",\"slug\":\"_4-单例模式\",\"link\":\"#_4-单例模式\",\"children\":[]}]},{\"level\":2,\"title\":\"三、结构型模式\",\"slug\":\"三、结构型模式\",\"link\":\"#三、结构型模式\",\"children\":[{\"level\":3,\"title\":\"1. 适配器模式\",\"slug\":\"_1-适配器模式\",\"link\":\"#_1-适配器模式\",\"children\":[]},{\"level\":3,\"title\":\"2. 装饰模式\",\"slug\":\"_2-装饰模式\",\"link\":\"#_2-装饰模式\",\"children\":[]},{\"level\":3,\"title\":\"3. 代理模式\",\"slug\":\"_3-代理模式\",\"link\":\"#_3-代理模式\",\"children\":[]}]},{\"level\":2,\"title\":\"四、行为型模式\",\"slug\":\"四、行为型模式\",\"link\":\"#四、行为型模式\",\"children\":[{\"level\":3,\"title\":\"1. 策略模式\",\"slug\":\"_1-策略模式\",\"link\":\"#_1-策略模式\",\"children\":[]},{\"level\":3,\"title\":\"2. 观察者模式\",\"slug\":\"_2-观察者模式\",\"link\":\"#_2-观察者模式\",\"children\":[]}]}],\"readingTime\":{\"minutes\":9.48,\"words\":2845},\"filePathRelative\":\"interview/designpattern.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
