export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"项目主页\",\"lang\":\"en-US\",\"frontmatter\":{\"home\":true,\"icon\":\"home\",\"title\":\"项目主页\",\"heroImage\":\"/logo.svg\",\"heroText\":\"编码人生—CodingLife\",\"tagline\":\"以 Java 项目为主线, 记录学习过程中的知识点\",\"actions\":[{\"text\":\"使用指南 💡\",\"link\":\"/base/\",\"type\":\"primary\"},{\"text\":\"文档\",\"link\":\"/base/\"}],\"features\":[{\"title\":\"edu项目源码\",\"icon\":\"slides\",\"details\":\"在线教育网后端代码，基于SpringBoot、SpringClound\",\"link\":\"https://github.com/CodingLifeVV/edu\"},{\"title\":\"edu-admin项目源码\",\"icon\":\"slides\",\"details\":\"在线教育网后端前端源码，基于vue开发，使用vue-admin-template模版\",\"link\":\"https://github.com/CodingLifeVV/edu-admin\"},{\"title\":\"edu-front项目源码\",\"icon\":\"slides\",\"details\":\"在线教育网后端前端\",\"link\":\"https://github.com/CodingLifeVV/edu-front\"},{\"title\":\"tiny-demo项目源码\",\"icon\":\"layout\",\"details\":\"文档中的一些小demo都在这里\",\"link\":\"https://github.com/CodingLifeVV/tiny-demo\"}],\"copyright\":false,\"footer\":\"MIT Licensed  <a href=\\\"https://beian.miit.gov.cn/#/Integrated/index\\\" target=\\\"_blank\\\">浙ICP备2022028662号-1</a> | Copyright © 2022-present <a href=\\\"https://github.com/CodingLifeVV\\\" target=\\\"_blank\\\">CodingLifeVV</a>\",\"summary\":\"在线教育网学习教程 项目简介 在线教育网源自谷粒学苑，分为前台用户系统和后台管理系统，使用现阶段主流技术实现，并对其中的部分技术进行了更新。后端 java 版本为 JDK17，涵盖了 SpringBoot、SpringCloud、Mybatis-Plus、Redis等技术。 后端技术及工具 技术 版本 说明 ------------- -----------\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/edu/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"编码人生\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"项目主页\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"项目简介\",\"slug\":\"项目简介\",\"link\":\"#项目简介\",\"children\":[{\"level\":3,\"title\":\"后端技术及工具\",\"slug\":\"后端技术及工具\",\"link\":\"#后端技术及工具\",\"children\":[]},{\"level\":3,\"title\":\"前端技术及工具\",\"slug\":\"前端技术及工具\",\"link\":\"#前端技术及工具\",\"children\":[]}]},{\"level\":2,\"title\":\"项目地址\",\"slug\":\"项目地址\",\"link\":\"#项目地址\",\"children\":[]},{\"level\":2,\"title\":\"交流学习\",\"slug\":\"交流学习\",\"link\":\"#交流学习\",\"children\":[]}],\"readingTime\":{\"minutes\":1.83,\"words\":548},\"filePathRelative\":\"README.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
