export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"项目主页\",\"lang\":\"en-US\",\"frontmatter\":{\"home\":true,\"icon\":\"home\",\"title\":\"项目主页\",\"heroImage\":\"/logo.png\",\"heroText\":\"编码人生—CodingLife\",\"tagline\":\"网站旨在分享学习过程中记录的一些笔记。目前包括三个大的模块：(1)在线教育网(2)SpringBoot系列(3)Java面试指南\",\"actions\":[{\"text\":\"快速上手 💡\",\"link\":\"/edu/guide/knowledge\",\"type\":\"primary\"},{\"text\":\"交流学习 📥\",\"link\":\"/#交流学习\"}],\"features\":[{\"title\":\"edu项目源码\",\"icon\":\"layout\",\"details\":\"在线教育网后端代码，基于SpringBoot、SpringClound\",\"link\":\"https://github.com/CodingLifeVV/edu\"},{\"title\":\"edu-admin项目源码\",\"icon\":\"layout\",\"details\":\"在线教育网后端前端源码，基于vue开发，使用vue-admin-template模版\",\"link\":\"https://github.com/CodingLifeVV/edu-admin\"},{\"title\":\"edu-front项目源码\",\"icon\":\"layout\",\"details\":\"在线教育网后端前端\",\"link\":\"https://github.com/CodingLifeVV/edu-front\"},{\"title\":\"tiny-demo项目源码\",\"icon\":\"layout\",\"details\":\"edu项目知识点拆分后的一些小demo都在这里\",\"link\":\"https://github.com/CodingLifeVV/springboot-demo\"},{\"title\":\"SpringBoot实战项目源码\",\"icon\":\"layout\",\"details\":\"SpringBoot系列项目源码\",\"link\":\"https://github.com/CodingLifeVV/tiny-demo\"}],\"copyright\":false,\"footer\":\"MIT Licensed  <a href=\\\"https://beian.miit.gov.cn/#/Integrated/index\\\" target=\\\"_blank\\\">浙ICP备2022028662号-1</a> | Copyright © 2022-present <a href=\\\"https://github.com/CodingLifeVV\\\" target=\\\"_blank\\\">CodingLifeVV</a> </p> 内容创作不易，引用请注明出处，网站已备案，切勿侵权\",\"summary\":\"项目简介 模块 简介 -------------- :----------------------------------------------------------- 在线教育网 在线教育网源自谷粒学苑，分为前台用户系统和后台管理系统，使用现阶段主流技术实现，并对其中的部分技术进行了更新。后端 java 版本为 JDK17，涵盖了 SpringBoot\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.bmrs.top/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"编码人生\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"项目主页\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":3,\"title\":\"后端技术及工具\",\"slug\":\"后端技术及工具\",\"link\":\"#后端技术及工具\",\"children\":[]},{\"level\":3,\"title\":\"前端技术及工具\",\"slug\":\"前端技术及工具\",\"link\":\"#前端技术及工具\",\"children\":[]},{\"level\":2,\"title\":\"项目地址及演示\",\"slug\":\"项目地址及演示\",\"link\":\"#项目地址及演示\",\"children\":[]},{\"level\":2,\"title\":\"交流学习\",\"slug\":\"交流学习\",\"link\":\"#交流学习\",\"children\":[]}],\"readingTime\":{\"minutes\":3.54,\"words\":1061},\"filePathRelative\":\"README.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
