export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"项目主页","i":"home"},["/index.html","/README.md"]],
  ["v-6c6de154","/base/Docker.html",{"t":"Docker入门"},["/base/Docker","/base/Docker.md"]],
  ["v-1455d425","/base/",{"t":"工具篇"},["/base/index.html","/base/README.md"]],
  ["v-4fd8a36c","/base/git.html",{"t":"Git入门"},["/base/git","/base/git.md"]],
  ["v-3c10a4de","/base/github.html",{"t":"Github入门"},["/base/github","/base/github.md"]],
  ["v-69817531","/base/mybatisplus.html",{"t":"mybatis-plus入门"},["/base/mybatisplus","/base/mybatisplus.md"]],
  ["v-2fa80702","/interview/Jvm.html",{"t":"JVM"},["/interview/Jvm","/interview/Jvm.md"]],
  ["v-71b3ae87","/interview/",{"t":"Java面试知识总结"},["/interview/index.html","/interview/README.md"]],
  ["v-2acde81b","/interview/concurrent.html",{"t":"线程"},["/interview/concurrent","/interview/concurrent.md"]],
  ["v-9bb96dd2","/interview/database.html",{"t":"SQL 基础"},["/interview/database","/interview/database.md"]],
  ["v-307c4264","/interview/designpattern.html",{"t":"设计模式"},["/interview/designpattern","/interview/designpattern.md"]],
  ["v-026a6ef0","/interview/javaEE.html",{"t":"Spring"},["/interview/javaEE","/interview/javaEE.md"]],
  ["v-31fca704","/interview/javaSE.html",{"t":"Java 基础"},["/interview/javaSE","/interview/javaSE.md"]],
  ["v-03111666","/interview/networks.html",{"t":""},["/interview/networks","/interview/networks.md"]],
  ["v-531a20a3","/interview/programs.html",{"t":"链表"},["/interview/programs","/interview/programs.md"]],
  ["v-791b0205","/interview/redis.html",{"t":"一、redis 基础知识"},["/interview/redis","/interview/redis.md"]],
  ["v-07b008f7","/springboot/",{"t":"工具篇"},["/springboot/index.html","/springboot/README.md"]],
  ["v-34fa457e","/springboot/springboot1.html",{"t":"SpringBoot 基础"},["/springboot/springboot1","/springboot/springboot1.md"]],
  ["v-36af1e1d","/springboot/springboot2.html",{"t":"SpringBoot Web 开发"},["/springboot/springboot2","/springboot/springboot2.md"]],
  ["v-3863f6bc","/springboot/springboot3.html",{"t":"SpringBoot员工管理系统"},["/springboot/springboot3","/springboot/springboot3.md"]],
  ["v-3a18cf5b","/springboot/springboot4.html",{"t":"SpringBoot整合数据库"},["/springboot/springboot4","/springboot/springboot4.md"]],
  ["v-3bcda7fa","/springboot/springboot5.html",{"t":"SpringBoot整合SpringSecurity"},["/springboot/springboot5","/springboot/springboot5.md"]],
  ["v-3d828099","/springboot/springboot6.html",{"t":"SpringBoot整合Shiro"},["/springboot/springboot6","/springboot/springboot6.md"]],
  ["v-3f375938","/springboot/springboot7.html",{"t":"SpringBoot整合Swagger"},["/springboot/springboot7","/springboot/springboot7.md"]],
  ["v-40ec31d7","/springboot/springboot8.html",{"t":"SpringBoot简单任务实现"},["/springboot/springboot8","/springboot/springboot8.md"]],
  ["v-42a10a76","/springboot/springboot9.html",{"t":"SpringBoot与分布式入门"},["/springboot/springboot9","/springboot/springboot9.md"]],
  ["v-9a7d9066","/edu/backend/",{"t":"后端"},["/edu/backend/index.html","/edu/backend/README.md"]],
  ["v-28e43eb2","/edu/backend/key.html",{"t":"技术要点"},["/edu/backend/key","/edu/backend/key.md"]],
  ["v-e199e2d0","/edu/backend/sql.html",{"t":"数据库概述"},["/edu/backend/sql","/edu/backend/sql.md"]],
  ["v-efed1908","/edu/front/front-01.html",{"t":"快速入门","i":"config"},["/edu/front/front-01","/edu/front/front-01.md"]],
  ["v-ec8367ca","/edu/front/front-02.html",{"t":"快速入门","i":"config"},["/edu/front/front-02","/edu/front/front-02.md"]],
  ["v-025ed4e5","/edu/guide/",{"t":"学习指南"},["/edu/guide/index.html","/edu/guide/README.md"]],
  ["v-12861550","/edu/guide/func.html",{"t":"项目架构及功能概述"},["/edu/guide/func","/edu/guide/func.md"]],
  ["v-251d5740","/edu/guide/knowledge.html",{"t":"学习路线"},["/edu/guide/knowledge","/edu/guide/knowledge.md"]],
  ["v-00d17fc6","/edu/springcloud/springcloud-1.html",{"t":"SpringCloud"},["/edu/springcloud/springcloud-1","/edu/springcloud/springcloud-1.md"]],
  ["v-02865865","/edu/springcloud/springcloud-2.html",{"t":"SpringCloud"},["/edu/springcloud/springcloud-2","/edu/springcloud/springcloud-2.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
