export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"项目主页","i":"home"},["/index.html","/README.md"]],
  ["v-6c6de154","/base/Docker.html",{"t":"Docker入门"},["/base/Docker","/base/Docker.md"]],
  ["v-1455d425","/base/",{"t":"学习指南"},["/base/index.html","/base/README.md"]],
  ["v-4fd8a36c","/base/git.html",{"t":"Git入门"},["/base/git","/base/git.md"]],
  ["v-3c10a4de","/base/github.html",{"t":"Github入门"},["/base/github","/base/github.md"]],
  ["v-69817531","/base/mybatisplus.html",{"t":"mybatis-plus入门"},["/base/mybatisplus","/base/mybatisplus.md"]],
  ["v-55f718be","/edu/front/front-01%20copy.html",{"t":"快速入门","i":"config"},["/edu/front/front-01 copy.html","/edu/front/front-01%20copy","/edu/front/front-01 copy.md","/edu/front/front-01%20copy.md"]],
  ["v-efed1908","/edu/front/front-01.html",{"t":"快速入门","i":"config"},["/edu/front/front-01","/edu/front/front-01.md"]],
  ["v-ec8367ca","/edu/front/front-02.html",{"t":"快速入门","i":"config"},["/edu/front/front-02","/edu/front/front-02.md"]],
  ["v-e919b68c","/edu/front/front-03.html",{"t":""},["/edu/front/front-03","/edu/front/front-03.md"]],
  ["v-00d17fc6","/edu/springcloud/springcloud-1.html",{"t":""},["/edu/springcloud/springcloud-1","/edu/springcloud/springcloud-1.md"]],
  ["v-02865865","/edu/springcloud/springcloud-2.html",{"t":""},["/edu/springcloud/springcloud-2","/edu/springcloud/springcloud-2.md"]],
  ["v-aa84e9fa","/edu/util/utils.html",{"t":""},["/edu/util/utils","/edu/util/utils.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
